### ISSUE TITLE
Failed to resolve entry for package.

### ISSUE THREAD

**Issue by zkanda** [eduardoborges/use-mask-input#8]
I get this error whenever I tries this package. Any hint on this one?

```
11:17:53 AM [vite] Internal server error: Failed to resolve entry for package "use-mask-input". The package may have incorrect main/module/exports specified in its package.json.
```

To reproduce:
```
npm create vite@latest my-react-app -- --template react-ts
npm install react-hook-form use-mask-input 
```

Create a test file, say Hello.tsx

```
import { useForm } from "react-hook-form";
import { withHookFormMask } from "use-mask-input";

export default function Hello() {
  const { register, control, watch } = useForm({
    defaultValues: {
      phone: "",
    },
  });
  const onSubmit = (data: any) => {
    console.log(data);
  };
  return (
    <form onSubmit={onSubmit}>
      <input
        type="text"
        {...withHookFormMask(register("phone"), [
          "(99) 9999 9999",
          "(99) 9 9999 9999",
        ])}
      />
      <button type="submit">Submit</button>
    </form>
  );
}
```

**Comment by eduardoborges** [comment]
I will investigate this.

**Comment by z1m1n** [comment]
I have similar issue:

`Field 'browser' doesn't contain a valid alias configuration`
![image](https://user-images.githubusercontent.com/5075434/217879168-4148241e-27b6-4635-b20a-0073e52db976.png)

Last working version is 3.0.0

**Comment by eduardoborges** [comment]
Hey @z1m1n & @zkanda all problems are fixed on 3.0.5. Plz update <3

**Comment by zkanda** [comment]
Hello, I upgraded to latest, and it now works with Vite, but it doesn't seems to work with Webpack. Since that's what our project uses. I could reproduce it using create-react app


```
npx create-react-app my-app --template typescript
```

Update App.tsx with same code from the first comment.

I get this console error:

```
Uncaught TypeError: inputmask__WEBPACK_IMPORTED_MODULE_1__ is not a function
    at o (withHookFormMask.ts:16:1)
    at App (App.tsx:18:1)
    at renderWithHooks (react-dom.development.js:15851:1)
    at mountIndeterminateComponent (react-dom.development.js:19603:1)
    at beginWork (react-dom.development.js:21127:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3703:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3761:1)
    at invokeGuardedCallback (react-dom.development.js:3833:1)
    at beginWork$1 (react-dom.development.js:26981:1)
    at performUnitOfWork (react-dom.development.js:26109:1)
```

**Comment by z1m1n** [comment]
@eduardoborges hey! I'm having exactly same issue as @zkanda (using webpack 5)

**Comment by eduardoborges** [comment]
@zkanda & @z1m1n i fixed this regression. Thanks for contribuiting <3
